# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: kyujlee <kyujlee@student.42seoul.kr>       +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2021/10/21 11:31:47 by kyujlee           #+#    #+#              #
#    Updated: 2021/10/28 13:27:44 by kyujlee          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #



SRCS_DIR = src

SRC = solong.c

all:
	gcc -lmlx -framework opengl -framework appkit $(SRCS_DIR)/$(SRC)
